export const data = {
  drinks: [
    {
      idDrink: '13499',
      strDrink: 'Oreo Mudslide',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Collins Glass',
      strInstructions:
        "Blend Vodka, Kahlua, Bailey's, ice-cream and the Oreo well in a blender. Pour into a large frosted glass. Garnish with whipped cream and a cherry.",
      strInstructionsES: null,
      strInstructionsDE:
        "Mischen Sie Wodka, Kahlua, Bailey's, Eis und den Oreo gut in einem Mixer. In ein großes mattiertes Glas geben. Mit Schlagsahne und einer Kirsche garnieren.",
      strInstructionsFR: null,
      strInstructionsIT:
        'Mescola bene Vodka, Kahlua, Baileys, gelato e un oreo in un frullatore. Versare in un grande bicchiere. Guarnire con panna montata e una ciliegia.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/tpwwut1468925017.jpg',
      strIngredient1: 'Vodka',
      strIngredient2: 'Kahlua',
      strIngredient3: 'Baileys irish cream',
      strIngredient4: 'Vanilla ice-cream',
      strIngredient5: 'Oreo cookie',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '1 oz ',
      strMeasure4: '2 scoops ',
      strMeasure5: '1 ',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-07-19 11:43:37',
    },
  ],
};
